name: tests
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run pimod OpenWRT example
        uses: Natur40/pimod@master
        with:
          pifile: examples/RPi-OpenWRT.Pifile
      - name: Run a multi-line script
        run:
        echo "\n
        FROM 2018-11-13-raspbian-stretch-lite.img\n
        PUMP 100M\n
        RUN raspi-config nonint do_serial 0\n
        \n
        RUN apt-get update\n
        RUN bash -c 'DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade'\n
        RUN apt-get install -y sl\n
        " > Upgrade.Pifile
        sudo ./pimod.sh Upgrade.Pifile
        dd if=Upgrade.img of=/dev/sdc bs=4M status=progress
